from setuptools import find_packages, setup

setup(
    name="mir-system",
    version="1.0.0",
    description="Music Information Retrieval — Semantic Audio Analysis & Similarity Engine",
    author="Your Name",
    author_email="you@example.com",
    url="https://github.com/yourusername/mir-system",
    license="MIT",
    python_requires=">=3.10",
    packages=find_packages(where="src") + find_packages(where="."),
    package_dir={"": "src"},
    install_requires=[
        "librosa>=0.10",
        "numpy>=1.26",
        "torch>=2.1",
        "torchaudio>=2.1",
        "scikit-learn>=1.4",
        "faiss-cpu>=1.8",
        "fastapi>=0.111",
        "uvicorn[standard]>=0.29",
        "pydantic>=2.7",
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-asyncio",
            "pytest-cov",
            "ruff",
            "mypy",
        ],
        "gpu": ["faiss-gpu"],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Multimedia :: Sound/Audio :: Analysis",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="music information retrieval, audio analysis, deep learning, similarity search, MIR",
)
